<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Canvasing Database</name>
   <tag></tag>
   <elementGuidId>0ec94d28-98da-43c4-9738-e44ce1ac95f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-source_entry-p2-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-source_entry-p2-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d1299294-1087-4f90-969d-37a26b6631b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>b8d9743a-ce45-45a0-80fd-d6856212ac06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-source_entry-p2-container</value>
      <webElementGuid>33277e6d-629f-4f97-8edc-d96b410f8cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>c52d556b-d4d2-4d9f-9227-5965818f4d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2498ba3a-584c-473d-9042-960d957b34ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Canvasing Database</value>
      <webElementGuid>989ece2f-e6ce-4447-8b33-262199b9f2ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×Canvasing Database</value>
      <webElementGuid>f0fdf910-90f2-474e-8e8b-7a767eaeec43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-source_entry-p2-container&quot;)</value>
      <webElementGuid>19ed0354-c9bc-4e8e-b82d-8e570cd56b02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-source_entry-p2-container']</value>
      <webElementGuid>4487bdda-c44c-4368-823a-ae4de2a25014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-endpoint']/section/div/div/div/div/span[2]/span/span/span</value>
      <webElementGuid>b75a158a-94bf-4f4c-b6fb-d6d4af5d6466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create New Leads'])[1]/following::span[5]</value>
      <webElementGuid>4e570648-cac1-4c06-a5cf-bd31bb6fe55c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage'])[1]/following::span[6]</value>
      <webElementGuid>d686de0a-bda9-49e2-8af1-12d71ade7a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Sub-Entry Source'])[1]/preceding::span[5]</value>
      <webElementGuid>43443edc-7e8f-4681-970e-fe5d693924f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/span/span</value>
      <webElementGuid>8aa67e42-8294-4230-b208-ca482f09f6fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-source_entry-p2-container' and @title = 'Canvasing Database' and (text() = '×Canvasing Database' or . = '×Canvasing Database')]</value>
      <webElementGuid>773dc797-e626-49c3-abaf-9b3bf1662197</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
