<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select Entry Source_1_2</name>
   <tag></tag>
   <elementGuidId>da501eea-157f-40a6-903b-fdfbbb936494</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-source_entry-p2-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-source_entry-p2-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7eb45e67-027c-43ad-9dbf-b88e8c947c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>41d3c1eb-8922-4943-b934-ac5b0c7647da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-source_entry-p2-container</value>
      <webElementGuid>9680f2d9-e69b-4ab4-9859-9b28ec5f8648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>4fd6e3b9-f5ba-4a60-9464-4a21fa6eb75a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>04f11d50-7e92-49af-a661-ec601f9e0d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Entry Source</value>
      <webElementGuid>76b7e978-01bc-40b0-aefd-82c07e290b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-source_entry-p2-container&quot;)</value>
      <webElementGuid>c09ca933-dcdc-40fc-80f4-fee9cef9910a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-source_entry-p2-container']</value>
      <webElementGuid>c60d3c87-b8a3-412a-82b8-409e324d5c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-endpoint']/section/div/div/div/div/span[2]/span/span/span</value>
      <webElementGuid>a9fc5067-0b9a-4e37-a03b-05364e3b3270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create New Leads'])[1]/following::span[5]</value>
      <webElementGuid>895fe688-b200-4222-9fc3-f1a1960117a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage'])[1]/following::span[6]</value>
      <webElementGuid>2dd0b7eb-9147-421d-b435-cd77ef9bfc81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required.'])[1]/preceding::span[4]</value>
      <webElementGuid>174fda16-419c-4458-8a4b-22b61dec4ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/span/span</value>
      <webElementGuid>e51f517b-cc93-4e14-84a1-e33432b24ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-source_entry-p2-container' and (text() = 'Select Entry Source' or . = 'Select Entry Source')]</value>
      <webElementGuid>41cd5171-434b-45ff-a42a-587ebaf10989</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
