<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PRIMARY</name>
   <tag></tag>
   <elementGuidId>65db2e7d-0361-46ad-8201-cc237beab2e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-link.text-center.tab-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'PRIMARY')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b4aa6a06-c40e-4f84-88dd-c9ca9b8b43b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link text-center tab-primary</value>
      <webElementGuid>70a5aad3-0542-4583-a042-e8d2f7c88b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#primary</value>
      <webElementGuid>b4584a69-ca86-4697-b513-ff01dfa5f46e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>673c638c-b90a-4e59-827e-75a3e490d500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>e253dfa6-acef-4ea4-b87e-bc7b0d1bc1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b5e75394-fd9e-498d-9d2c-df4849993b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PRIMARY</value>
      <webElementGuid>ccb9a4ea-7c1c-4dd1-b311-877ac7ec1231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fixed sidebar-light sidebar-left-collapsed report SalesFunnel index js flexbox flexboxlegacy no-touch csstransforms csstransforms3d no-overflowscrolling webkit chrome win js no-mobile-device custom-scroll&quot;]/body[1]/section[@class=&quot;body&quot;]/div[@class=&quot;inner-wrapper&quot;]/section[@class=&quot;content-body&quot;]/div[@class=&quot;container-fluid bg-white&quot;]/div[@class=&quot;row mt-4&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;tabs tabs-custom mb-4&quot;]/ul[@class=&quot;nav nav-tabs&quot;]/li[@class=&quot;nav-item col-xs-6 col-sm-2&quot;]/a[@class=&quot;nav-link text-center tab-primary&quot;]</value>
      <webElementGuid>adad52e7-64d2-438c-b12d-9c458c68ec61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PRIMARY')]</value>
      <webElementGuid>270fb923-c188-4b39-ae66-23570825d904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom Date'])[1]/following::a[1]</value>
      <webElementGuid>e68d18fb-c582-4a80-b255-100350bc5c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales Funnel'])[1]/following::a[1]</value>
      <webElementGuid>860ea1e1-a982-45cb-b326-dc16d7c371c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SECONDARY'])[1]/preceding::a[1]</value>
      <webElementGuid>0f134133-fdd2-4acc-9d4d-1b34a701a59e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::a[2]</value>
      <webElementGuid>2ad07fd9-ad05-4ff6-b5db-f3c50a1076ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PRIMARY']/parent::*</value>
      <webElementGuid>127cd2cc-5acc-4809-b87e-c94777e0078d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#primary')]</value>
      <webElementGuid>ef6c46c5-bac4-46c3-a2e8-f95a30e88a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/ul/li/a</value>
      <webElementGuid>e1f9ec21-1534-4cd8-91b2-c04f3d6ecd5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#primary' and (text() = 'PRIMARY' or . = 'PRIMARY')]</value>
      <webElementGuid>0cd8a7a8-d77e-490d-9451-092a4b991c60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
