<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SECONDARY</name>
   <tag></tag>
   <elementGuidId>a4b2ff69-50fc-401b-bb3b-50f7f4a470f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-link.text-center.tab-secondary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'SECONDARY')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3e0b0660-9a60-4c98-9791-5cea4472bd0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link text-center tab-secondary</value>
      <webElementGuid>91aaad46-a8b5-4469-8823-144f59ddf706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#secondary</value>
      <webElementGuid>686c09a2-f9dc-4d75-9a1c-ba12ee753d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>secondary</value>
      <webElementGuid>a3f5b2c6-fc1d-4b1b-bfef-02ec55937857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>a0268619-dfb7-4cbe-9c7a-7853b8f30eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SECONDARY</value>
      <webElementGuid>31d39c22-9a16-4dff-833d-4e1cbb455474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fixed sidebar-light sidebar-left-collapsed report SalesFunnel index js flexbox flexboxlegacy no-touch csstransforms csstransforms3d no-overflowscrolling webkit chrome win js no-mobile-device custom-scroll&quot;]/body[1]/section[@class=&quot;body&quot;]/div[@class=&quot;inner-wrapper&quot;]/section[@class=&quot;content-body&quot;]/div[@class=&quot;container-fluid bg-white&quot;]/div[@class=&quot;row mt-4&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;tabs tabs-custom mb-4&quot;]/ul[@class=&quot;nav nav-tabs&quot;]/li[@class=&quot;nav-item col-xs-6 col-sm-2&quot;]/a[@class=&quot;nav-link text-center tab-secondary&quot;]</value>
      <webElementGuid>651367c2-131f-4e95-b3b8-e7a839d2fb56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SECONDARY')]</value>
      <webElementGuid>db113ddb-d9e6-43dc-bebf-b07fa700c9f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRIMARY'])[1]/following::a[1]</value>
      <webElementGuid>c02adefc-039c-47f2-89ce-7a8fb8d3d181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom Date'])[1]/following::a[2]</value>
      <webElementGuid>a84f62a6-3338-4c79-8225-378714430318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::a[1]</value>
      <webElementGuid>cadef8bc-0eda-4f6f-87e6-2d669ef434ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(ST) AA Test 5 Mbois ilakes'])[1]/preceding::a[1]</value>
      <webElementGuid>05eb9eda-d526-4294-802c-eed0794e6b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SECONDARY']/parent::*</value>
      <webElementGuid>27d607db-5814-49b5-87bc-389d56e340ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#secondary')]</value>
      <webElementGuid>8a559d3b-b340-496b-bb8f-ce0013dee008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/ul/li[2]/a</value>
      <webElementGuid>49d17bd6-4069-45c2-9fc0-243235b080c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#secondary' and (text() = 'SECONDARY' or . = 'SECONDARY')]</value>
      <webElementGuid>1ff7143b-ff28-4cb1-89f7-f8d1238fe7f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
