<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Custom Date_fa fa-caret-down pull-right mt-2</name>
   <tag></tag>
   <elementGuidId>77bb3fe9-6d32-4a21-92d3-906b64b84a55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-caret-down.pull-right.mt-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='date-filter']/i[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ba1f7de5-3b29-4d73-9dc1-f68e40c5a0d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-caret-down pull-right mt-2</value>
      <webElementGuid>402ee5d7-5445-4ba4-81cd-35447b7bbdf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;date-filter&quot;)/i[@class=&quot;fa fa-caret-down pull-right mt-2&quot;]</value>
      <webElementGuid>c46b4dfb-e4c8-44b1-bed5-10b8e95a8b73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='date-filter']/i[2]</value>
      <webElementGuid>7d8872a2-88ee-4a11-950f-806547349a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i[2]</value>
      <webElementGuid>5179a8b2-56fa-451b-86ff-1a55ca48543a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
